[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port %(ENV_PORT)s --workers %(ENV_UVICORN_WORKERS)s --proxy-headers --forwarded-allow-ips *
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A app.core.celery worker --loglevel=%(ENV_CELERY_LOGLEVEL)s --pool=%(ENV_CELERY_POOL)s --concurrency=%(ENV_CELERY_CONCURRENCY)s --queues=%(ENV_CELERY_QUEUES)s
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
