import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.session import engine, Base, AsyncSessionLocal
from app.crud.crud_notification import notification_crud
from app.schemas.notification import NotificationCreate
from app.crud.user import user_crud

async def seed_notifications():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as db:
        # Find a user to seed notifications for
        user = await user_crud.get_by_email(db, email="solo@lawyer.com") # Using test user from TESTING_GUIDE.md
        if not user:
            print("Test user solo@lawyer.com not found. Getting first available user.")
            from sqlalchemy import select
            from app.db.models.user import User
            result = await db.execute(select(User).limit(1))
            user = result.scalars().first()
            if not user:
                print("No users in the database to seed notifications for.")
                return

        user_id = user.id
        org_id = user.organization_id or 1 # Fallback if independent user

        print(f"Seeding 100 notifications for user {user.email} (ID: {user_id}, Org: {org_id})")

        for i in range(100):
            notif_in = NotificationCreate(
                user_id=user_id,
                organization_id=org_id,
                type="system",
                title=f"Test Notification {i+1}",
                message=f"This is a test notification generated by the seed script. Message ID {i+1} follows the 100 notification performance limit.",
                source_type="system",
                source_id=i+1
            )
            await notification_crud.create(db=db, obj_in=notif_in)
            if i % 10 == 0:
                print(f"Created {i} notifications...")

        print("Successfully seeded 100 notifications.")

if __name__ == "__main__":
    asyncio.run(seed_notifications())
