"""add deadlines table

Revision ID: 249567856343
Revises: 21e496a0ea8f
Create Date: 2026-03-12 14:41:54.903327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249567856343'
down_revision: Union[str, Sequence[str], None] = '21e496a0ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'deadlinetype') THEN
                CREATE TYPE deadlinetype AS ENUM (
                    'HEARING', 'FILING', 'RESPONSE', 'APPEAL', 'STATUTE_OF_LIMITATIONS', 'OTHER'
                );
            END IF;
        END $$;
    """)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS deadlines (
            id SERIAL NOT NULL,
            document_id INTEGER NOT NULL,
            case_id INTEGER,
            organization_id INTEGER,
            deadline_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            deadline_type deadlinetype NOT NULL,
            description VARCHAR,
            confidence_score DOUBLE PRECISION,
            created_at TIMESTAMP WITHOUT TIME ZONE,
            updated_at TIMESTAMP WITHOUT TIME ZONE,
            PRIMARY KEY (id),
            FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE,
            FOREIGN KEY(document_id) REFERENCES documents (id) ON DELETE CASCADE,
            FOREIGN KEY(organization_id) REFERENCES organizations (id) ON DELETE CASCADE
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_case_id ON deadlines (case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_document_id ON deadlines (document_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_id ON deadlines (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_organization_id ON deadlines (organization_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_organization_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_document_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_case_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
