"""add_email_inbound_fields

Revision ID: 2ed57e67a0fa
Revises: e178fd83e900
Create Date: 2026-03-08 16:48:28.767967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed57e67a0fa'
down_revision: Union[str, Sequence[str], None] = 'e178fd83e900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS ingestion_method VARCHAR(20)")
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS email_from VARCHAR(255)")
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS email_subject VARCHAR(512)")
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS email_received_at TIMESTAMP WITHOUT TIME ZONE")
    # Create email_configs if it doesn't exist
    op.execute("""
        CREATE TABLE IF NOT EXISTS email_configs (
            id SERIAL NOT NULL,
            user_id INTEGER,
            provider VARCHAR NOT NULL,
            access_token VARCHAR,
            refresh_token VARCHAR,
            token_expiry TIMESTAMP WITHOUT TIME ZONE,
            email_address VARCHAR,
            is_active BOOLEAN DEFAULT true,
            created_at TIMESTAMP WITHOUT TIME ZONE,
            updated_at TIMESTAMP WITHOUT TIME ZONE,
            PRIMARY KEY (id)
        )
    """)
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS organization_id INTEGER")
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS inbound_slug VARCHAR(60)")
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS webhook_secret VARCHAR(64)")
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS ingestion_enabled BOOLEAN")
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS total_ingested INTEGER")
    op.execute("ALTER TABLE email_configs ADD COLUMN IF NOT EXISTS last_received_at TIMESTAMP WITHOUT TIME ZONE")
    op.alter_column('email_configs', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_email_configs_inbound_slug ON email_configs (inbound_slug)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'email_configs_organization_id_fkey'
            ) THEN
                ALTER TABLE email_configs
                ADD CONSTRAINT email_configs_organization_id_fkey
                FOREIGN KEY (organization_id) REFERENCES organizations (id);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_configs', type_='foreignkey')
    op.drop_index(op.f('ix_email_configs_inbound_slug'), table_name='email_configs')
    op.alter_column('email_configs', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('email_configs', 'last_received_at')
    op.drop_column('email_configs', 'total_ingested')
    op.drop_column('email_configs', 'ingestion_enabled')
    op.drop_column('email_configs', 'webhook_secret')
    op.drop_column('email_configs', 'inbound_slug')
    op.drop_column('email_configs', 'organization_id')
    op.drop_column('documents', 'email_received_at')
    op.drop_column('documents', 'email_subject')
    op.drop_column('documents', 'email_from')
    op.drop_column('documents', 'ingestion_method')
    # ### end Alembic commands ###
