"""update deadlines for manual management

Revision ID: 5d33cbf66774
Revises: df974d0d427a
Create Date: 2026-03-12 22:01:15.772472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d33cbf66774'
down_revision: Union[str, Sequence[str], None] = 'df974d0d427a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS assignee_id INTEGER")
    op.execute("ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS created_by_id INTEGER")
    op.execute("ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS title VARCHAR")
    op.execute("ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS is_completed BOOLEAN")
    op.execute("ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITHOUT TIME ZONE")
    op.alter_column('deadlines', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_assignee_id ON deadlines (assignee_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_deadlines_created_by_id ON deadlines (created_by_id)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'deadlines_assignee_id_fkey'
            ) THEN
                ALTER TABLE deadlines
                ADD CONSTRAINT deadlines_assignee_id_fkey
                FOREIGN KEY (assignee_id) REFERENCES users (id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'deadlines_created_by_id_fkey'
            ) THEN
                ALTER TABLE deadlines
                ADD CONSTRAINT deadlines_created_by_id_fkey
                FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_index(op.f('ix_deadlines_created_by_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_assignee_id'), table_name='deadlines')
    op.alter_column('deadlines', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('deadlines', 'completed_at')
    op.drop_column('deadlines', 'is_completed')
    op.drop_column('deadlines', 'title')
    op.drop_column('deadlines', 'created_by_id')
    op.drop_column('deadlines', 'assignee_id')
    # ### end Alembic commands ###
