"""Add processing tracking

Revision ID: 21e496a0ea8f
Revises: 2ed57e67a0fa
Create Date: 2026-03-08 18:14:42.965596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e496a0ea8f'
down_revision: Union[str, Sequence[str], None] = '2ed57e67a0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_analysis', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('processing_stage', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('processing_progress', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('processed_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'processed_chunks')
    op.drop_column('documents', 'processing_progress')
    op.drop_column('documents', 'processing_stage')
    op.drop_column('document_chunks', 'chunk_analysis')
    # ### end Alembic commands ###
