"""add deadlines table

Revision ID: 249567856343
Revises: 21e496a0ea8f
Create Date: 2026-03-12 14:41:54.903327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249567856343'
down_revision: Union[str, Sequence[str], None] = '21e496a0ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('deadline_date', sa.DateTime(), nullable=False),
    sa.Column('deadline_type', sa.Enum('HEARING', 'FILING', 'RESPONSE', 'APPEAL', 'STATUTE_OF_LIMITATIONS', 'OTHER', name='deadlinetype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_case_id'), 'deadlines', ['case_id'], unique=False)
    op.create_index(op.f('ix_deadlines_document_id'), 'deadlines', ['document_id'], unique=False)
    op.create_index(op.f('ix_deadlines_id'), 'deadlines', ['id'], unique=False)
    op.create_index(op.f('ix_deadlines_organization_id'), 'deadlines', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_organization_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_document_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_case_id'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
