"""add_email_inbound_fields

Revision ID: 2ed57e67a0fa
Revises: e178fd83e900
Create Date: 2026-03-08 16:48:28.767967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed57e67a0fa'
down_revision: Union[str, Sequence[str], None] = 'e178fd83e900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ingestion_method', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('email_from', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('email_subject', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('email_received_at', sa.DateTime(), nullable=True))
    op.add_column('email_configs', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('email_configs', sa.Column('inbound_slug', sa.String(length=60), nullable=True))
    op.add_column('email_configs', sa.Column('webhook_secret', sa.String(length=64), nullable=True))
    op.add_column('email_configs', sa.Column('ingestion_enabled', sa.Boolean(), nullable=True))
    op.add_column('email_configs', sa.Column('total_ingested', sa.Integer(), nullable=True))
    op.add_column('email_configs', sa.Column('last_received_at', sa.DateTime(), nullable=True))
    op.alter_column('email_configs', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_email_configs_inbound_slug'), 'email_configs', ['inbound_slug'], unique=True)
    op.create_foreign_key(None, 'email_configs', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_configs', type_='foreignkey')
    op.drop_index(op.f('ix_email_configs_inbound_slug'), table_name='email_configs')
    op.alter_column('email_configs', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('email_configs', 'last_received_at')
    op.drop_column('email_configs', 'total_ingested')
    op.drop_column('email_configs', 'ingestion_enabled')
    op.drop_column('email_configs', 'webhook_secret')
    op.drop_column('email_configs', 'inbound_slug')
    op.drop_column('email_configs', 'organization_id')
    op.drop_column('documents', 'email_received_at')
    op.drop_column('documents', 'email_subject')
    op.drop_column('documents', 'email_from')
    op.drop_column('documents', 'ingestion_method')
    # ### end Alembic commands ###
