"""update deadlines for manual management

Revision ID: 5d33cbf66774
Revises: df974d0d427a
Create Date: 2026-03-12 22:01:15.772472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d33cbf66774'
down_revision: Union[str, Sequence[str], None] = 'df974d0d427a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('deadlines', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('deadlines', sa.Column('title', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('deadlines', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('deadlines', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_deadlines_assignee_id'), 'deadlines', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_deadlines_created_by_id'), 'deadlines', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'deadlines', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'deadlines', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.drop_index(op.f('ix_deadlines_created_by_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_assignee_id'), table_name='deadlines')
    op.alter_column('deadlines', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('deadlines', 'completed_at')
    op.drop_column('deadlines', 'is_completed')
    op.drop_column('deadlines', 'title')
    op.drop_column('deadlines', 'created_by_id')
    op.drop_column('deadlines', 'assignee_id')
    # ### end Alembic commands ###
