"""add ai_battery_save_mode to organization

Revision ID: df974d0d427a
Revises: 249567856343
Create Date: 2026-03-12 17:35:48.178039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df974d0d427a'
down_revision: Union[str, Sequence[str], None] = '249567856343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations ADD COLUMN IF NOT EXISTS ai_battery_save_mode BOOLEAN")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ai_battery_save_mode')
    # ### end Alembic commands ###
