"""upgrade_audit_logs

Revision ID: e178fd83e900
Revises: ac9e1900e546
Create Date: 2026-03-04 19:06:14.810936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e178fd83e900'
down_revision: Union[str, Sequence[str], None] = 'ac9e1900e546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    # Create organizations table (renamed from organisations, with extra fields)
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('plan', sa.String(), nullable=False, server_default='free'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_organizations_name'),
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.add_column('audit_logs', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('http_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('path', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('hash', sa.String(length=64), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_hash'), 'audit_logs', ['hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_previous_hash'), 'audit_logs', ['previous_hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'action')
    op.create_foreign_key(None, 'cases', 'clients', ['client_id'], ['id'])
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.drop_constraint(op.f('document_tag_association_tag_id_fkey'), 'document_tag_association', type_='foreignkey')
    op.drop_constraint(op.f('document_tag_association_document_id_fkey'), 'document_tag_association', type_='foreignkey')
    op.create_foreign_key(None, 'document_tag_association', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_tag_association', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'),
               nullable=True,
               existing_server_default=sa.text("'COMPLETED'::documentprocessingstatus"))
    op.drop_column('documents', 'embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embeddings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('documents', 'processing_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentprocessingstatus'),
               nullable=False,
               existing_server_default=sa.text("'COMPLETED'::documentprocessingstatus"))
    op.drop_constraint(None, 'document_tag_association', type_='foreignkey')
    op.drop_constraint(None, 'document_tag_association', type_='foreignkey')
    op.create_foreign_key(op.f('document_tag_association_document_id_fkey'), 'document_tag_association', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('document_tag_association_tag_id_fkey'), 'document_tag_association', 'tags', ['tag_id'], ['id'])
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_previous_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'hash')
    op.drop_column('audit_logs', 'previous_hash')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'path')
    op.drop_column('audit_logs', 'http_method')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'event_type')
    op.create_table('organisations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organisations_pkey'))
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=True)
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    # ### end Alembic commands ###
