from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel

class SummaryBase(BaseModel):
    document_id: int
    content: str
    key_dates: Optional[List[str]] = None
    parties: Optional[List[str]] = None
    missing_documents_suggestion: Optional[str] = None

class SummaryCreate(BaseModel):
    # This will be generated by AI, so we might only pass a document_id to the trigger
    document_id: int
    content: str
    key_dates: Optional[List[str]] = None
    parties: Optional[List[str]] = None
    missing_documents_suggestion: Optional[str] = None

class SummaryUpdate(BaseModel):
    content: Optional[str] = None
    key_dates: Optional[List[str]] = None
    parties: Optional[List[str]] = None
    missing_documents_suggestion: Optional[str] = None

class Summary(SummaryBase):
    id: int
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
